import './styles/main.scss'
import type { Metadata } from 'next'
import { Yeseva_One } from 'next/font/google'
import { Footer } from './components';

const yesevaOne = Yeseva_One({ subsets: ['latin'], weight: ['400'], variable: '--font-serif', });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={yesevaOne.variable}>
        {children}
        <Footer />
      </body>
    </html>
  )
}
